# Generated by Django 5.2.8 on 2025-12-11 02:31

import sketch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchwork',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=sketch.models.upload_path),
        ),
    ]
